# Generated by Django 4.1.2 on 2022-10-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookadmin', '0001_initial'),
        ('bookuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedbookitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookuser.bookuser'),
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookadmin.author'),
        ),
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ManyToManyField(to='bookadmin.category'),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bookadmin.publisher'),
        ),
    ]
